### PR TITLE
fix memory leaking

### PR DESCRIPTION
**Pull request by R15User**
fix memory leaking by destroying the textures after drawing text

### CODE REVIEW

**Review by mandar1jn — APPROVED** [review]
should work. But poly probably won't merge it (because he never checks PR's)

**Review by 19wintersp — APPROVED** [review]

**Comment by mandar1jn** [comment]
Question: is the issue in rendercopy or freesurface? You destroy the texture in the functions containing freesurface, but you are referencing a variable that isn’t used by freesurface. There are other functions also using rendercopy. Why don’t you destroy the textures on those?

**Comment by PolyMarsDev** [comment]
can't believe I overlooked that, THANK YOU

**Comment by R15User** [comment]
> Question: is the issue in rendercopy or freesurface? You destroy the texture in the functions containing freesurface, but you are referencing a variable that isn’t used by freesurface. There are other functions also using rendercopy. Why don’t you destroy the textures on those?

the issue is in the create texture from surface, it is running every frame and allocating memory without clearing it. the Destroy function fixes that

**Comment by mandar1jn** [comment]
Ok

**Pull request merged**
